"""Export the hotspots the model carries a site effect for, as SQL to seed the app.

    python pipeline/export_hotspots.py   ->  data/hotspots.sql

WHY SHIP THIS RATHER THAN CALL EBIRD AT RUNTIME
The app could ask eBird for hotspots near the user, but the model only knows
the ones it was fitted on — every other hotspot falls back to the pooled county
baseline, so a live query mostly returns places the model cannot speak to. A
static table means every pin on the map has a real site effect behind it, and
the app needs no eBird key, no server-side proxy and no cache.

Hotspots change slowly enough that regenerating this alongside a monthly refit
is more than often enough.

Names come from eBird's region hotspot endpoint (one call). Coordinates come
from the same place. The visit count is from our own scrape and is what the UI
should use to convey how much evidence sits behind a site.
"""
import json
import os
import sys
from pathlib import Path

import duckdb
import requests
from dotenv import load_dotenv

ROOT = Path(__file__).parent.parent
load_dotenv(ROOT / ".env")
COEF = ROOT / "data" / "model_coefficients.json"
OUT = ROOT / "data" / "hotspots.sql"
REGION = os.getenv("SCRAPE_REGION", "US-PA-003")


def modelled_sites():
    """The loc_ids that got their own coefficient, i.e. not the pooled baseline."""
    models = json.loads(COEF.read_text())
    if not models:
        sys.exit(f"{COEF.name} is empty — run fit_logit.py first.")
    sites = next(iter(models.values()))["site"]
    return sorted(s for s in sites if s != "PERSONAL")


def names(region):
    """locId -> hotspot record, for every hotspot in the region's STATE.

    Asked of the state, not the county. This looked up one county's hotspot
    list and silently dropped any modelled site missing from it — which was
    invisible while the model was one county and destroyed the release the
    moment it was not. The 2026-08-26 refit fitted sites across sixteen
    counties, found 118 of its 155 sites absent from Allegheny's list, skipped
    them, and published 37 hotspots where the previous model had 209.

    Nothing downstream could catch it. hotspots.json is what the app tests
    coverage against, so shrinking it shrank the forecastable area, the map
    extent derived from it, and the postal codes derived from that — all
    consistently, all wrong, and all reported as a successful run.

    /ref/hotspot/US-PA returns every hotspot in the state in one call, which is
    the same cost as one county and cannot go stale by geography.
    """
    state = "-".join(region.split("-")[:2])
    r = requests.get(f"https://api.ebird.org/v2/ref/hotspot/{state}",
                     headers={"X-eBirdApiToken": os.environ["EBIRD_API_KEY"].strip()},
                     params={"fmt": "json"}, timeout=90)
    r.raise_for_status()
    return {h["locId"]: h for h in r.json()}


def visits():
    con = duckdb.connect(str(ROOT / "data" / "birding.duckdb"), read_only=True)
    out = {r[0]: r[1] for r in con.execute(
        "select loc_id, count(*) from checklists group by 1").fetchall()}
    con.close()
    return out


def q(s):
    return s.replace("'", "''")


if __name__ == "__main__":
    sites = modelled_sites()
    ref = names(REGION)
    n = visits()

    missing = [s for s in sites if s not in ref]
    if missing:
        # a hotspot can be retired or merged after we scraped it, so a few
        # missing is ordinary attrition
        print(f"warning: {len(missing)} modelled sites have no current eBird "
              f"entry and are skipped: {missing[:5]}")

    # ...but a large share missing is not attrition, it is the lookup being
    # wrong — asking the wrong region, a bad key, a truncated response. That
    # happened on 2026-08-26 and published 37 hotspots in place of 209, which
    # then shrank the coverage, the extent and the postal code list in step,
    # while the run reported success. Refuse instead: this file is what the app
    # tests coverage against, and quietly emitting a fraction of it is worse
    # than emitting nothing.
    if sites and len(missing) > 0.2 * len(sites):
        sys.exit(
            f"{len(missing)} of {len(sites)} modelled sites are absent from the "
            f"eBird reference for {'-'.join(REGION.split('-')[:2])}.\n"
            "That is too many to be hotspots going out of service. Check that "
            "the reference covers every county the model was fitted on before "
            "publishing a hotspot list this incomplete.")
    rows = [f"  ('{s}', '{q(ref[s]['locName'])}', {ref[s]['lat']:.6f}, "
            f"{ref[s]['lng']:.6f}, {n.get(s, 0)})"
            for s in sites if s in ref]

    OUT.write_text(
        "-- The eBird hotspots the model carries a site effect for.\n"
        "-- Generated by pipeline/export_hotspots.py — safe to re-run.\n"
        "-- Static on purpose: only these have coefficients, so a live query\n"
        "-- would mostly return places the model cannot speak to.\n"
        "create table if not exists hotspots (\n"
        "  loc_id        text primary key,\n"
        "  name          text not null,\n"
        "  latitude      double precision not null,\n"
        "  longitude     double precision not null,\n"
        "  n_checklists  integer not null\n"
        ");\n\n"
        "delete from hotspots;\n"
        "insert into hotspots (loc_id, name, latitude, longitude, n_checklists) "
        "values\n" + ",\n".join(rows) + ";\n")

    print(f"wrote {OUT.name}: {len(rows)} hotspots, "
          f"{OUT.stat().st_size / 1024:.0f} KB")
