"""Push fitted coefficients to wherever the app reads them.

The app needs a lookup table, not a model object. This writes one row per
(species, term) so the forecast function can select what it needs and add up.

Two destinations, either or both:

  SUPABASE_URL + SUPABASE_SERVICE_KEY   ->  model_coefficients table
  HF_TOKEN + HF_DATASET                 ->  a Hugging Face dataset repo

With neither set it writes SQL to data/model_coefficients.sql, which you can
paste into a SQL editor. That is the zero-setup path.
"""
import json
import os
from pathlib import Path

from dotenv import load_dotenv

ROOT = Path(__file__).parent.parent
# without this a local run reads none of the credentials the other scripts do,
# so the same command publishes to different places depending on the machine
load_dotenv(ROOT / ".env")
SRC = ROOT / "data" / "model_coefficients.json"
SQL_OUT = ROOT / "data" / "model_coefficients.sql"

SCALARS = ("intercept", "log_dur", "log_dist", "n_observers", "traveling",
           "wind_max", "temp_mean", "precip_sum", "cloud_mean")


def flatten(models):
    """{species: {...}} -> [(species, term, value), ...]"""
    rows = []
    for sp, m in models.items():
        for k in SCALARS:
            if k in m:
                rows.append((sp, k, float(m[k])))
        for h, v in m.get("hour", {}).items():
            rows.append((sp, f"hour_{int(h):02d}", float(v)))
        for w, v in m.get("week", {}).items():
            rows.append((sp, f"week_{int(w):02d}", float(v)))
        # one term per hotspot; PERSONAL is the pooled baseline for the
        # locations the app never shows
        for site, v in m.get("site", {}).items():
            rows.append((sp, f"site_{site}", float(v)))
        # support counts let the app grey out hours it cannot stand behind
        for h, n in m.get("hour_support", {}).items():
            rows.append((sp, f"support_{int(h):02d}", float(n)))
        meta = m.get("_meta", {})
        if "detections" in meta:
            rows.append((sp, "meta_detections", float(meta["detections"])))
        # new_day is the app's real use: a known hotspot on a future date.
        # new_site is the harder case and the honest number for a map pin
        # the model has barely seen.
        for split in ("by_date", "by_site"):
            for k, v in (meta.get(split) or {}).items():
                rows.append((sp, f"meta_{split}_{k}", float(v)))
    return rows


BATCH = 2000


def to_sql(rows, models, header=True):
    """One transaction, but batched INSERTs.

    A single statement with every row is valid SQL and Postgres will take it,
    but a browser-based editor parses the whole thing in the page and a
    17,000-tuple statement is enough to hang the tab. Batching also makes a
    failure point to a range of rows rather than to the whole load.
    """
    species = sorted(models)
    lines = []
    if header:
        lines += ["-- generated by pipeline/publish.py — safe to re-run",
                  "begin;",
                  "delete from model_coefficients where species_code in ("
                  + ", ".join(f"'{s}'" for s in species) + ");"]
    for i in range(0, len(rows), BATCH):
        vals = [f"  ('{sp}', '{term}', {val:.6g})"
                for sp, term, val in rows[i:i + BATCH]]
        lines.append("insert into model_coefficients "
                     "(species_code, term, value) values")
        lines.append(",\n".join(vals) + ";")
    if header:
        lines.append("commit;")
    return "\n".join(lines)


def write_chunks(rows, models, n=6):
    """Split the load into files small enough to paste one at a time.

    The fallback path when there are no Supabase credentials: a 694 KB paste
    is beyond what a chat box or an editor textarea handles comfortably.

    Each file stands alone — no begin/commit spanning them. A browser SQL
    editor runs every paste on its own connection, so a transaction opened in
    one file would never be committed by the next.
    """
    out = []
    size = -(-len(rows) // n)
    for i in range(0, len(rows), size):
        part = i // size + 1
        p = SQL_OUT.with_name(f"model_coefficients_{part:02d}.sql")
        head = [f"-- part {part} of {n} — run the parts in order."]
        if part == 1:
            head.append("delete from model_coefficients where species_code in ("
                        + ", ".join(f"'{s}'" for s in sorted(models)) + ");")
        else:
            # no semicolon in this comment — a proper parser ignores one, but
            # anything that splits statements naively would break the file here
            head.append("-- part 1 clears the old rows, so do not skip it")
        body = "\n".join(head) + "\n" + to_sql(rows[i:i + size], models,
                                               header=False)
        p.write_text(body + "\n")
        out.append(p)
    return out


def push_supabase(rows, models, url, key):
    import requests
    species = sorted(models)
    hdr = {"apikey": key, "Authorization": f"Bearer {key}",
           "Content-Type": "application/json", "Prefer": "return=minimal"}
    # replace this species' rows rather than accumulating stale terms
    q = ",".join(f'"{s}"' for s in species)
    requests.delete(f"{url}/rest/v1/model_coefficients"
                    f"?species_code=in.({q})", headers=hdr, timeout=60
                    ).raise_for_status()
    payload = [{"species_code": s, "term": t, "value": v} for s, t, v in rows]
    for i in range(0, len(payload), 1000):
        requests.post(f"{url}/rest/v1/model_coefficients", headers=hdr,
                      json=payload[i:i + 1000], timeout=120).raise_for_status()
    return len(payload)


def push_hf(repo, token):
    from huggingface_hub import HfApi
    HfApi(token=token).upload_file(
        path_or_fileobj=str(SRC), path_in_repo="model_coefficients.json",
        repo_id=repo, repo_type="dataset",
        commit_message="refit coefficients")
    return repo


if __name__ == "__main__":
    models = json.loads(SRC.read_text())
    rows = flatten(models)
    print(f"{len(models)} species, {len(rows):,} coefficient rows")

    url, key = os.getenv("SUPABASE_URL"), os.getenv("SUPABASE_SERVICE_KEY")
    if url and key:
        n = push_supabase(rows, models, url.rstrip("/"), key)
        print(f"pushed {n:,} rows to Supabase")

    repo, token = os.getenv("HF_DATASET"), os.getenv("HF_TOKEN")
    if repo and token:
        print(f"uploaded model_coefficients.json to {push_hf(repo, token)}")

    # always, not as a fallback: the SQL file is what gets pasted into the
    # app's editor by hand, and it was needed exactly when a HF token was
    # also set — treating the upload as "done" made it silently disappear
    SQL_OUT.write_text(to_sql(rows, models))
    print(f"wrote {SQL_OUT.name} ({SQL_OUT.stat().st_size/1024:.0f} KB)")
    if not (url and key):
        parts = write_chunks(rows, models)
        print(f"also wrote {len(parts)} smaller parts to paste in order:")
        for p in parts:
            print(f"  {p.name}  ({p.stat().st_size/1024:.0f} KB)")
        print("or set SUPABASE_URL and SUPABASE_SERVICE_KEY to push directly")
