"""Push fitted coefficients to wherever the app reads them.

The app needs a lookup table, not a model object. This writes one row per
(species, term) so the forecast function can select what it needs and add up.

Two destinations, either or both:

  SUPABASE_URL + SUPABASE_SERVICE_KEY   ->  model_coefficients table
  HF_TOKEN + HF_DATASET                 ->  a Hugging Face dataset repo

With neither set it writes SQL to data/model_coefficients.sql, which you can
paste into a SQL editor. That is the zero-setup path.
"""
import json
import os
from pathlib import Path

ROOT = Path(__file__).parent.parent
SRC = ROOT / "data" / "model_coefficients.json"
SQL_OUT = ROOT / "data" / "model_coefficients.sql"

SCALARS = ("intercept", "log_dur", "log_dist", "n_observers", "traveling",
           "wind_max", "temp_mean", "precip_sum", "cloud_mean")


def flatten(models):
    """{species: {...}} -> [(species, term, value), ...]"""
    rows = []
    for sp, m in models.items():
        for k in SCALARS:
            if k in m:
                rows.append((sp, k, float(m[k])))
        for h, v in m.get("hour", {}).items():
            rows.append((sp, f"hour_{int(h):02d}", float(v)))
        for w, v in m.get("week", {}).items():
            rows.append((sp, f"week_{int(w):02d}", float(v)))
        # one term per hotspot; PERSONAL is the pooled baseline for the
        # locations the app never shows
        for site, v in m.get("site", {}).items():
            rows.append((sp, f"site_{site}", float(v)))
        # support counts let the app grey out hours it cannot stand behind
        for h, n in m.get("hour_support", {}).items():
            rows.append((sp, f"support_{int(h):02d}", float(n)))
        meta = m.get("_meta", {})
        if "detections" in meta:
            rows.append((sp, "meta_detections", float(meta["detections"])))
        # new_day is the app's real use: a known hotspot on a future date.
        # new_site is the harder case and the honest number for a map pin
        # the model has barely seen.
        for split in ("by_date", "by_site"):
            for k, v in (meta.get(split) or {}).items():
                rows.append((sp, f"meta_{split}_{k}", float(v)))
    return rows


def to_sql(rows, models):
    species = sorted(models)
    lines = ["-- generated by pipeline/publish.py — safe to re-run",
             "begin;",
             "delete from model_coefficients where species_code in ("
             + ", ".join(f"'{s}'" for s in species) + ");",
             "insert into model_coefficients (species_code, term, value) values"]
    vals = [f"  ('{sp}', '{term}', {val:.6g})" for sp, term, val in rows]
    lines.append(",\n".join(vals) + ";")
    lines.append("commit;")
    return "\n".join(lines)


def push_supabase(rows, models, url, key):
    import requests
    species = sorted(models)
    hdr = {"apikey": key, "Authorization": f"Bearer {key}",
           "Content-Type": "application/json", "Prefer": "return=minimal"}
    # replace this species' rows rather than accumulating stale terms
    q = ",".join(f'"{s}"' for s in species)
    requests.delete(f"{url}/rest/v1/model_coefficients"
                    f"?species_code=in.({q})", headers=hdr, timeout=60
                    ).raise_for_status()
    payload = [{"species_code": s, "term": t, "value": v} for s, t, v in rows]
    for i in range(0, len(payload), 1000):
        requests.post(f"{url}/rest/v1/model_coefficients", headers=hdr,
                      json=payload[i:i + 1000], timeout=120).raise_for_status()
    return len(payload)


def push_hf(repo, token):
    from huggingface_hub import HfApi
    HfApi(token=token).upload_file(
        path_or_fileobj=str(SRC), path_in_repo="model_coefficients.json",
        repo_id=repo, repo_type="dataset",
        commit_message="refit coefficients")
    return repo


if __name__ == "__main__":
    models = json.loads(SRC.read_text())
    rows = flatten(models)
    print(f"{len(models)} species, {len(rows):,} coefficient rows")

    did = False
    url, key = os.getenv("SUPABASE_URL"), os.getenv("SUPABASE_SERVICE_KEY")
    if url and key:
        n = push_supabase(rows, models, url.rstrip("/"), key)
        print(f"pushed {n:,} rows to Supabase")
        did = True

    repo, token = os.getenv("HF_DATASET"), os.getenv("HF_TOKEN")
    if repo and token:
        print(f"uploaded model_coefficients.json to {push_hf(repo, token)}")
        did = True

    if not did:
        SQL_OUT.write_text(to_sql(rows, models))
        print(f"no credentials set — wrote {SQL_OUT.name} "
              f"({SQL_OUT.stat().st_size/1024:.0f} KB)")
        print("paste it into your SQL editor, or set SUPABASE_URL / HF_TOKEN")
